swagger: '2.0'
info:
  title: Kayvee Logger Service
  description: Logs kayvee events.
  version: "1.0.0"
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /ping:
    get:
      operationId: ping
      summary: Ping
      responses:
        200:
          description: All's good
  /log:
    post:
      operationId: log
      summary: Logs a given JSON-formatted kayvee event.
      parameters:
        - name: event
          in: body
          required: true
          schema:
            type: string
      responses:
        200:
          description: All's good
        400:
          description: Invalid kayvee event JSON.
