package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/middleware"
)

// NewLogParams creates a new LogParams object
// with the default values initialized.
func NewLogParams() LogParams {
	var ()
	return LogParams{}
}

// LogParams contains all the bound params for the log operation
// typically these are obtained from a http.Request
//
// swagger:parameters log
type LogParams struct {
	/*
	  Required: true
	  In: body
	*/
	Event string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *LogParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	var body string
	if err := route.Consumer.Consume(r.Body, &body); err != nil {
		res = append(res, errors.NewParseError("event", "body", "", err))
	} else {

		if len(res) == 0 {
			o.Event = body
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
