package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"
)

/*LogOK All's good

swagger:response logOK
*/
type LogOK struct {
}

// NewLogOK creates LogOK with default headers values
func NewLogOK() *LogOK {
	return &LogOK{}
}

// WriteResponse to the client
func (o *LogOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
}

/*LogBadRequest Invalid kayvee event JSON.

swagger:response logBadRequest
*/
type LogBadRequest struct {
}

// NewLogBadRequest creates LogBadRequest with default headers values
func NewLogBadRequest() *LogBadRequest {
	return &LogBadRequest{}
}

// WriteResponse to the client
func (o *LogBadRequest) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(400)
}
